import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Logo from "../../assets/images/logo.png"
import slide01 from "../assets/images/logo-dark-small.png"
import slide02 from "../assets/images/slides/promo-b.png"
import slide03 from "../assets/images/slides/promo-c.png"

// const inter = Inter({ subsets: ["latin"] });

const  Home = () => {
  return (
    <>
      <Head>
        <title>Admin-Rediger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
    <h1>Admin Rediger!</h1>
    </>
  );
}
export default Home;
