import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import AdminDashboard from "@/components/dashboard/adminDashboard";

// const inter = Inter({ subsets: ["latin"] });

const Home = () => {
  return (
    <>
      <Head>
        <title>Admin-Rediger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className="nk-content" style={{ position: "relative", marginTop: "65px" }}>
        <div className="container-fluid">
          <div className="nk-content-inner">
            <div className="nk-content-body">
              <AdminDashboard />
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
export default Home;
